pipeline:
  greenkeeper_update_lockfile:
    image: node:9
    commands:
      - npm install -g git+https://github.com/donny-dont/greenkeeper-lockfile.git#4edd3391f956fd1288bff8195af2ea74a678cfdc
      - greenkeeper-lockfile-update
    when:
      branch: greenkeeper*
        
  build:
    image: node:9
    commands:
      - printenv
      - echo 'HELLO WORLD I R DRONE'
      - npm i -g npm@latest
      - npm ci
    environment:
      - TEST=foo-${NODE_VERSION}.tar
      
  greenkeeper_lockfile_upload:
    image: node:9
    secrets: [gh_token]
    commands:
      - npm install -g git+https://github.com/donny-dont/greenkeeper-lockfile.git#4edd3391f956fd1288bff8195af2ea74a678cfdc
      - greenkeeper-lockfile-upload
    when:
      branch: greenkeeper*
