pipeline:
  greenkeeper_update_lockfile:
    image: plugins/greenkeeper
    update: true
    when:
      branch: greenkeeper/*
        
  build:
    image: node:10
    commands:
      - npm i -g npm@latest
      - npm ci
      
  greenkeeper_lockfile_upload:
    image: plugins/greenkeeper
    upload: true
    secrets: 
      - source: gh_token
        target: gk_token
    when:
      branch: greenkeeper/*
