pipeline:
  greenkeeper_update_lockfile:
    image: node:9
    commands:
      - printenv
      - git status
      - git branch
      - git fetch --all
      - git checkout ${DRONE_COMMIT_BRANCH}
      - npm install -g git+https://github.com/donny-dont/greenkeeper-lockfile.git#c46c832725468b9b8540c092aa40abd4563ffa0f
      - greenkeeper-lockfile-update
#    when:
#      branch: greenkeeper*
        
  build:
    image: node:9
    commands:
      - printenv
      - echo 'HELLO WORLD I R DRONE'
      - npm i -g npm@latest
      - npm ci
    environment:
      - TEST=foo-${NODE_VERSION}.tar
      
  greenkeeper_lockfile_upload:
    image: node:9
    commands:
      - git rev-parse --abbrev-ref HEAD
      - npm install -g git+https://github.com/donny-dont/greenkeeper-lockfile.git#c46c832725468b9b8540c092aa40abd4563ffa0f
      - greenkeeper-lockfile-upload
#    when:
#      branch: greenkeeper*
