pipeline:
  greenkeeper_update_lockfile:
    image: node:9
    commands:
      - printenv
      - npm install -g git+https://github.com/donny-dont/greenkeeper-lockfile.git#1728ac0cba364d6575d54c079bd8a6ada3adbacd
      - greenkeeper-lockfile-update
#    when:
#      branch: greenkeeper*
        
  build:
    image: node:9
    commands:
      - printenv
      - echo 'HELLO WORLD I R DRONE'
      - npm i -g npm@latest
      - npm ci
    environment:
      - TEST=foo-${NODE_VERSION}.tar
      
  greenkeeper_lockfile_upload:
    image: node:9
    commands:
      - git rev-parse --abbrev-ref HEAD
      - npm install -g git+https://github.com/donny-dont/greenkeeper-lockfile.git#1728ac0cba364d6575d54c079bd8a6ada3adbacd
      - greenkeeper-lockfile-upload
#    when:
#      branch: greenkeeper*
